//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventDetail()
        {
            this.ServiceEvents = new HashSet<ServiceEvent>();
        }
    
        public int Id { get; set; }
        public string TypeOfEvent { get; set; }
        public int CustomerId { get; set; }
        public int StaffId { get; set; }
        public int LocationId { get; set; }
        public string Notes { get; set; }
        public int Duration { get; set; }
        public System.DateTime Date { get; set; }
        public int Guests { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceEvent> ServiceEvents { get; set; }
    }
}
